repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-toml
# Python
-   repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
    -   id: black-jupyter
-   repo: https://github.com/charliermarsh/ruff-pre-commit
    # Ruff version.
    rev: v0.0.263
    hooks:
    - id: ruff
      args: ["--fix"]
